// <auto-generated />
using System;
using EF.CH.Extensions;
using KeylessSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeylessSample.Migrations
{
    [DbContext(typeof(KeylessDbContext))]
    [Migration("20251129122829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KeylessSample.ApiRequest", b =>
                {
                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("RequestBody")
                        .HasColumnType("String");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("Int32");

                    b.Property<int>("StatusCode")
                        .HasColumnType("Int32");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime64(3)");

                    b.ToTable("ApiRequests", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseMergeTree(b, "Timestamp", "Endpoint");
                    ClickHouseEntityTypeBuilderExtensions.HasPartitionBy(b, "toYYYYMM(\"Timestamp\")");
                    ClickHouseEntityTypeBuilderExtensions.HasTtl(b, "\"Timestamp\" + INTERVAL 90 DAY");
                });

            modelBuilder.Entity("KeylessSample.PageView", b =>
                {
                    b.Property<int>("DurationMs")
                        .HasColumnType("Int32");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("Referrer")
                        .HasColumnType("String");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime64(3)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("String");

                    b.Property<string>("UserId")
                        .HasColumnType("String");

                    b.ToTable("PageViews", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseMergeTree(b, "Timestamp", "PageUrl");
                    ClickHouseEntityTypeBuilderExtensions.HasPartitionBy(b, "toYYYYMMDD(\"Timestamp\")");
                });

            modelBuilder.Entity("KeylessSample.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime64(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DateTime64(3)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseReplacingMergeTree(b, "UpdatedAt", new[] { "Id" });
                });
#pragma warning restore 612, 618
        }
    }
}
