using EF.CH.Extensions;
using EF.CH.TempTable;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Testcontainers.ClickHouse;
using Xunit;

namespace EF.CH.Tests.Features;

/// <summary>
/// The auto-generated temp-table name historically used 8 hex chars from a
/// GUID — 32 bits of entropy, ~50% birthday-paradox collision odds at √2³² ≈ 65k
/// concurrently-living tables. That's reachable in CI fleets sharing a server.
/// Pin the generated name's entropy to the full 32-char hex form (~128 bits).
/// </summary>
public class TempTableNamingTests : IAsyncLifetime
{
    private readonly ClickHouseContainer _container = new ClickHouseBuilder()
        .WithImage("clickhouse/clickhouse-server:25.6")
        .Build();

    public Task InitializeAsync() => _container.StartAsync();
    public Task DisposeAsync() => _container.DisposeAsync().AsTask();

    [Fact]
    public async Task AutoGeneratedTempTableName_HasAtLeast16HexCharsOfEntropy()
    {
        await using var ctx = Create();
        await ctx.Database.EnsureCreatedAsync();
        var manager = ctx.GetService<IClickHouseTempTableManager>();

        await using var handle = await manager.CreateAsync<NamingRow>();

        var prefix = $"_tmp_{nameof(NamingRow)}_";
        Assert.StartsWith(prefix, handle.TableName);

        var entropy = handle.TableName[prefix.Length..];
        Assert.True(entropy.Length >= 16,
            $"expected ≥16 hex chars of entropy, got {entropy.Length} in '{handle.TableName}'");
        Assert.Matches("^[0-9a-fA-F]+$", entropy);
    }

    private NamingCtx Create() =>
        new(new DbContextOptionsBuilder<NamingCtx>()
            .UseClickHouse(_container.GetConnectionString())
            .Options);

    public sealed class NamingRow
    {
        public uint Id { get; set; }
    }

    public sealed class NamingCtx(DbContextOptions<NamingCtx> o) : DbContext(o)
    {
        public DbSet<NamingRow> Rows => Set<NamingRow>();
        protected override void OnModelCreating(ModelBuilder mb)
            => mb.Entity<NamingRow>(e =>
            {
                e.ToTable("naming_rows");
                e.HasKey(x => x.Id);
                e.UseMergeTree(x => x.Id);
            });
    }
}
