// <auto-generated />
using System;
using EF.CH.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationSample;

#nullable disable

namespace MigrationSample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20251129123751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MigrationSample.EventLog", b =>
                {
                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<string>("Metadata")
                        .HasColumnType("String");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime64(3)");

                    b.Property<string>("UserId")
                        .HasColumnType("String");

                    b.ToTable("EventLogs", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseMergeTree(b, "Timestamp", "EventType");
                    ClickHouseEntityTypeBuilderExtensions.HasPartitionBy(b, "toYYYYMMDD(\"Timestamp\")");
                });

            modelBuilder.Entity("MigrationSample.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("DateTime64(3)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("UUID");

                    b.Property<int>("Quantity")
                        .HasColumnType("Int32");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseMergeTree(b, "OrderDate", "Id");
                    ClickHouseEntityTypeBuilderExtensions.HasPartitionBy(b, "toYYYYMM(\"OrderDate\")");
                });

            modelBuilder.Entity("MigrationSample.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime64(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String");

                    b.Property<decimal>("Price")
                        .HasColumnType("Decimal(18, 4)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    ClickHouseEntityTypeBuilderExtensions.UseMergeTree(b, "Id");
                });
#pragma warning restore 612, 618
        }
    }
}
